### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Bahm9919** [Nathanieljla/cg3d-maya-casc#3]
Documents\maya\modules\cascadeur\scripts\wingcarrier\pigeons\cascadeur.py line 125: 'utf-8' codec can't decode byte 0x88 in position 0: invalid start byte

Tried with maya 2022 and 2023.

Cascadeaur 2024.1.1

Tried with just boxes.

**Comment by Bahm9919** [comment]
Solved.

1.Just go to file ...\scripts\wingcarrier\pigeons\cascadeur.py

1.1 Open with text editor.

2.Find -  output = subprocess.check_output(call).decode()

3.replace with - output = subprocess.check_output(call).decode("utf-8")

**Comment by Nathanieljla** [comment]
@Bahm9919 Thanks for the info.  I've only seen one other person report an issue with some decoding issues and they were using Maya with the simplified Chinese language pack.  Is that your case as well?  I'll make that change in the official wing-carrier repository.

**Comment by Bahm9919** [comment]
> @Bahm9919 Thanks for the info.  I've only seen one other person report an issue with some decoding issues and they were using Maya with the simplified Chinese language pack.  Is that your case as well?  I'll make that change in the official wing-carrier repository. 

English version. But maybe the problem was with operation system language, anyway, great plugin mate. Thank you.
